version: '3.9'

services:
  web-node-1:
    image: nginx:latest
    container_name: web-node-1
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    networks:
      - html-cluster

  web-node-2:
    image: nginx:latest
    container_name: web-node-2
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    networks:
      - html-cluster

  web-node-3:
    image: nginx:latest
    container_name: web-node-3
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    networks:
      - html-cluster

networks:
  html-cluster:
    driver: bridge
